import Head from 'next/head'
import { useQuery } from '@apollo/client'
import { GET_EMPLOYEES } from '../graphql/query'
import LoadingContainer from '../components/LoadingContainer'
import EmployeeCard from '../components/EmployeeCard'
import type { Employee } from '../types'
import { Box } from '@mui/material'
export default function Home() {
  const { data, loading } = useQuery(GET_EMPLOYEES)

  return (
    <Box>
      <Head>
        <title>Goal app</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <LoadingContainer isLoading={loading}>
        <Box
          sx={{
            display: 'grid',
            gridTemplateColumns: 'repeat(2, 1fr)',
            columnGap: '2rem',
            rowGap: '2rem',
          }}
        >
          {data?.employees?.map((employee: Employee) => {
            return <EmployeeCard employee={employee} key={employee.id} />
          })}
        </Box>
      </LoadingContainer>
    </Box>
  )
}
